### ISSUE TITLE
AttributeError: module 'black' has no attribute 'is_docstring'

### ISSUE THREAD

**Issue by natarajanc-prodigygame** [inspera/blackbricks#12]
when i tried in a new virtualenv with `black==21.4b0` and `blackbricks, version 0.6.2`
```sh
$ blackbricks --check      /Users/natarajan.chakrapani/repos/prodigy-databricks/notebooks/ETL/jdbc_query_to_lake.py
Traceback (most recent call last):
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/bin/blackbricks", line 8, in <module>
    sys.exit(app())
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/blackbricks/cli.py", line 192, in main
    check=check,
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/blackbricks/cli.py", line 32, in process_files
    output = format_str(content, config=format_config)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/blackbricks/blackbricks.py", line 112, in format_str
    cell, mode=black.FileMode(line_length=config.line_length)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/__init__.py", line 832, in format_str
    for current_line in lines.visit(src_node):
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 164, in visit
    yield from self.visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/linegen.py", line 101, in visit_default
    yield from super().visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 170, in visit_default
    yield from self.visit(child)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 162, in visit
    yield from visitf(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/linegen.py", line 171, in visit_simple_stmt
    yield from self.visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/linegen.py", line 101, in visit_default
    yield from super().visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 170, in visit_default
    yield from self.visit(child)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 164, in visit
    yield from self.visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/linegen.py", line 101, in visit_default
    yield from super().visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 170, in visit_default
    yield from self.visit(child)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 164, in visit
    yield from self.visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/linegen.py", line 101, in visit_default
    yield from super().visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 170, in visit_default
    yield from self.visit(child)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 164, in visit
    yield from self.visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/linegen.py", line 101, in visit_default
    yield from super().visit_default(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 170, in visit_default
    yield from self.visit(child)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/black/nodes.py", line 162, in visit
    yield from visitf(node)
  File "/Users/natarajan.chakrapani/repos/prodigy-databricks/test/lib/python3.7/site-packages/blackbricks/blackbricks.py", line 57, in patch_visit_STRING
    if black.is_docstring(leaf) and "\\\n" not in leaf.value:
AttributeError: module 'black' has no attribute 'is_docstring'
```

However 

if i  i tried in a new virtualenv with a previous black version `black==20.8b1` and `blackbricks, version 0.6.2` this works 

```sh
$ blackbricks --check      /Users/natarajan.chakrapani/repos/prodigy-databricks/notebooks/ETL/jdbc_query_to_lake.py
would reformat /Users/natarajan.chakrapani/repos/prodigy-databricks/notebooks/ETL/jdbc_query_to_lake.py
All done!
1 files would be reformatted
```

**Comment by bsamseth** [comment]
Hi! Thanks for reporting this. Black seems to have done some refactoring with the latest update, which broke some of the patch code used in blackbricks. Easy enough to fix, see 3e56574bfc4ff158b9c0b0ff8a66411fa5cd409a. New release on PyPI now, requiring the newer black version. https://github.com/inspera/blackbricks/releases/tag/0.6.3
